name: health-tracker

services:
  health-tracker:
    build:
      context: .
    container_name: health-tracker
    restart: unless-stopped
    ports:
      - "8095:80"
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - ./data:/data
